server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081/
          predicates:
            - Path=/admin_product/**
        - id: user
          uri: http://localhost:8082/
          predicates:
            - Path=/admin_user/**
